name: Bug Report
about: File a bug report
title: "Bug: "
labels:
  - bug
  - not fixed
assignees: Smug246

body:
  - type: textarea
    id: what-you-expected
    attributes:
      label: What Did You Expect To Happen?
      placeholder: Please describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      placeholder: Please describe exactly what happened
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Add Screenshots
      placeholder: Please include screenshots of any errors in the terminal/s
    validations:
      required: true

  - type: dropdown
    id: options
    attributes:
      label: What Options Did You Select?
      multiple: true
      options:
        - Add To Startup
        - Disable Defender
        - Discord Info
        - Fake Error
        - Kill Protector
        - Wifi Info
        - Ping
        - Anti Debug/VM
        - Minecraft Info
        - System Info
        - 2FA Codes
        - Browser Info
        - Roblox Info
        - Obfuscation
        - Injection
        - Anti Spam
        - Self Destruct
        - File Pumper

  - type: checkboxes
    id: terms
    attributes:
      label: "Check the following before submitting (If Applicable)"
      options:
        - label: I have checked the existing issues
          required: true

        - label: I have followed the installation steps
          required: true

        - label: I have attempted to resolve my problem by myself
          required: true
