name: Feature Request
description: Suggest a feature request
title: "feature:"
labels: ["enhancement"]
assignees: Smug246
body:
  - type: textarea
    id: what-feature
    attributes:
      label: What Feature?
      placeholder: Add description of feature
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add Screenshots
      placeholder: Add screenshots
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Check the following before submitting (If Applicable)"
      options:
        - label: I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
          required: true

        - label: I want to work on this feature